#!/bin/bash

DEBUG="-n"

CURRENT=$(grep -m1 "<version>" pom.xml | sed -E "s/\s*<version>(.*)<\/version>\s*/\\1/")
RELEASE=${CURRENT//-SNAPSHOT/}
NEXT_MINOR==$(($(echo $RELEASE | sed -E "s/([0-9]\.){2}//") + 1 ))
MAJOR=$(echo $RELEASE | sed -E "s/([0-9])$//")
NEXT=$MAJOR$NEXT_MINOR"-SNAPSHOT"

# update versions
mvn tycho-versions:set-version $RELEASE

# try
mvn -U clean test

# prepare
git commit -a -m "Preparing release v"$RELEASE
git tag -a "v$RELEASE" -m "version $RELEASE"

# release
mvn install -P uploadRelease


# next iteration
mvn tycho-versions:set-version $NEXT

git commit -a -m "Preparing next development version v"$NEXT

# push everything to origin
git push $DEBUG
git push $DEBUG --tags
